CREATE TABLE ASIGNATURA (
	CODASIG number(3),
	NOMBRE VARCHAR2(30),
	NUMHORAS number (3),
	CONSTRAINT pk_asignaura	 PRIMARY KEY (CODASIG)	
	);
	
CREATE TABLE ALUMNO(
	DNI VARCHAR2(9) NOT NULL, 
	NOMBRE VARCHAR2(30) NOT NULL,
	APELLIDO1 VARCHAR2(50) NOT NULL,
	APELLIDO2 VARCHAR2(50) NULL,
	CONSTRAINT pk_alumno PRIMARY KEY (DNI)
	);
	
	-----TABLA DE RELACIONE
CREATE TABLE INSCRIPCION(
	CODASIG NUMBER (3),
	DNI VARCHAR2 (9),
	CALIFICACION NUMBER (2),
	CONSTRAINT pk_inscripcion PRIMARY KEY (CODASIG, DNI),
	CONSTRAINT fk_asignatura FOREIGNKEY (CODASIG) REFERENCES ASIGNATURA(CODASIG),
	CONSTRAINT fk_alumno 	FOREIGN KEY (DNI) REFERENCES (ALUMNO (DNI)
	);